### ISSUE TITLE
documentation 

### ISSUE THREAD

**Issue by ORCA666** [jungjin0003/WinHook#1]
hii, much respect for uploading your wonderful code to the public, but i just wanted to ask, if you could add little bit more documentations about how to use it, i saw the example of messagebox hooking but i really didn't understand what was happening, and if i wanted to hook functions like createProcess, openprocess , does your code work ??

thank you very much and i hope you have a nice day

**Comment by jungjin0003** [comment]
Do you wanted hook the CreateProcess, OpenProcess function? If so, this code works. and If you tell me what you didn't understand, I'll add it to the document.

**Comment by alexa872** [comment]
> Do you wanted hook the CreateProcess, OpenProcess function? If so, this code works. and If you tell me what you didn't understand, I'll add it to the document.

hay mate i think i need a global hook to hook functions in other processes, if this code can do it, i just want to know how, i really thank you but its been a while after your last reply and i want some help  😁😁

thank you for your attention
